force-app/main/default/objects/Instance__c/Instance__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Instance__c/fields/Number_of_Licences__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Licences__c</fullName>
    <label>Number of Licences</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Instance__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <description>Total Quantity of products</description>
    <label>Total Quantity</label>
    <summarizedField>OpportunityLineItem.Quantity</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler.cls
public with sharing class OpportunityTriggerHandler {

    public static void createInstances(List<Opportunity> newOpportunities) {
        List<Opportunity> wonOpps = new List<Opportunity>();
        for(Opportunity opp : newOpportunities) {
            if(opp.IsWon) {
                wonOpps.add(opp);
            }
        }

        if(wonOpps.isEmpty()) {
            return;
        }

        List<Opportunity> oppsWithAccountNames = [SELECT AccountId, Account.Name, Total_Quantity__c FROM Opportunity WHERE ID IN : wonOpps];

        List<Instance__c> newInstances = new List<Instance__c>();
        for(Opportunity opp : oppsWithAccountNames) {
            newInstances.add(makeInstance(opp));
        }

        insert newInstances;
    }

    private static Instance__c makeInstance(Opportunity newOpp) {
        Instance__c newInst = new Instance__c();
        newInst.Name = newOpp.Account.Name + ' Standard Instance';
        newInst.Type__c = 'Standard';
        newInst.Account__c = newOpp.AccountId;
        newInst.Number_of_Licences__c = newOpp.Total_Quantity__c;
      
        return newInst;
    }
}